"""create email delivery attempts table

Revision ID: 93dfda21cf4f
Revises: 9d6e7f8091a2
Create Date: 2026-08-09 04:10:37.141806

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93dfda21cf4f"
down_revision: str | Sequence[str] | None = "9d6e7f8091a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_delivery_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email_draft_id", sa.Integer(), nullable=False),
        sa.Column("attempt_key", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("recipient_email", sa.String(length=254), nullable=False),
        sa.Column("envelope_from", sa.String(length=254), nullable=False),
        sa.Column("header_from_email", sa.String(length=254), nullable=False),
        sa.Column("header_from_name", sa.String(length=100), nullable=True),
        sa.Column("reply_to", sa.String(length=254), nullable=True),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("transport_name", sa.String(length=100), nullable=False),
        sa.Column("security_mode", sa.String(length=30), nullable=False),
        sa.Column("smtp_classification", sa.String(length=20), nullable=True),
        sa.Column("smtp_code", sa.Integer(), nullable=True),
        sa.Column("error_category", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unknown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(outcome = 'RESERVED' AND completed_at IS NULL "
            "AND accepted_at IS NULL AND unknown_at IS NULL "
            "AND smtp_classification IS NULL AND smtp_code IS NULL "
            "AND error_category IS NULL) OR "
            "(outcome = 'ACCEPTED' AND completed_at IS NOT NULL "
            "AND accepted_at IS NOT NULL AND unknown_at IS NULL "
            "AND smtp_classification IS NULL AND error_category IS NULL) OR "
            "(outcome = 'TRANSIENT_FAILURE' AND completed_at IS NOT NULL "
            "AND accepted_at IS NULL AND unknown_at IS NULL "
            "AND smtp_classification = 'TRANSIENT') OR "
            "(outcome = 'PERMANENT_FAILURE' AND completed_at IS NOT NULL "
            "AND accepted_at IS NULL AND unknown_at IS NULL "
            "AND smtp_classification = 'PERMANENT') OR "
            "(outcome = 'UNKNOWN' AND completed_at IS NOT NULL "
            "AND accepted_at IS NULL AND unknown_at IS NOT NULL "
            "AND smtp_classification = 'UNKNOWN')",
            name="ck_email_delivery_attempts_outcome_fields",
        ),
        sa.CheckConstraint(
            "length(trim(attempt_key)) = 64 AND lower(attempt_key) = attempt_key AND "
            "length(trim(recipient_email)) > 0 AND "
            "length(trim(envelope_from)) > 0 AND "
            "length(trim(header_from_email)) > 0 AND "
            "(header_from_name IS NULL OR length(trim(header_from_name)) > 0) AND "
            "(reply_to IS NULL OR length(trim(reply_to)) > 0) AND "
            "length(trim(message_id)) > 0 AND "
            "length(trim(content_hash)) = 64 AND lower(content_hash) = content_hash AND "
            "length(trim(transport_name)) > 0 AND "
            "security_mode IN ('STARTTLS', 'TLS_IMPLICIT', "
            "'PLAINTEXT_LOCAL_TEST_ONLY')",
            name="ck_email_delivery_attempts_nonblank_identity",
        ),
        sa.CheckConstraint(
            "outcome IN ('RESERVED', 'ACCEPTED', 'TRANSIENT_FAILURE', "
            "'PERMANENT_FAILURE', 'UNKNOWN')",
            name="ck_email_delivery_attempts_outcome",
        ),
        sa.CheckConstraint(
            "smtp_classification IS NULL OR "
            "smtp_classification IN ('TRANSIENT', 'PERMANENT', 'UNKNOWN')",
            name="ck_email_delivery_attempts_classification",
        ),
        sa.CheckConstraint(
            "smtp_code IS NULL OR (smtp_code >= 200 AND smtp_code <= 599)",
            name="ck_email_delivery_attempts_smtp_code",
        ),
        sa.ForeignKeyConstraint(
            ["email_draft_id"],
            ["email_drafts.id"],
            name="fk_email_delivery_attempts_email_draft_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_key", name="uq_email_delivery_attempts_attempt_key"),
        sa.UniqueConstraint("email_draft_id", name="uq_email_delivery_attempts_email_draft_id"),
        sa.UniqueConstraint("message_id", name="uq_email_delivery_attempts_message_id"),
    )
    op.create_index(
        "ix_email_delivery_attempts_created_at",
        "email_delivery_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_email_delivery_attempts_outcome",
        "email_delivery_attempts",
        ["outcome"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_delivery_attempts_outcome", table_name="email_delivery_attempts")
    op.drop_index("ix_email_delivery_attempts_created_at", table_name="email_delivery_attempts")
    op.drop_table("email_delivery_attempts")
    # ### end Alembic commands ###
